#!/bin/bash
qrc="$1"
if [ ! -f "$qrc".in ]; then
    echo "Input file $qrc.in not found"
    exit 2
fi
set -eu
cat "$qrc".in | \
    sed -e 's/@GETVERSION_PRIMARY@//g' | \
    grep -v '@GETVERSION_ALTERNATE@' | \
    sed -e 's/@SUFFIX@/.so/g' -e 's/@EXESUFFIX@//g' \
	> "$qrc"
