#!/bin/bash

set -eu

case $(git status --porcelain --untracked-files=no) in
    "") ;;
    *) echo "ERROR: Current working copy has been modified - not proceeding"; exit 2;;
esac

version=`perl -p -e 's/^[^"]*"([^"]*)".*$/$1/' version.h`

mkdir -p packages
echo

if [ -d /Applications ]; then

    app="Vamp Plugin Pack Installer"
    volume="$app"-"$version"
    dmg="$volume".dmg

    deploy/osx/build-and-package.sh

    mv "$dmg" packages/

else

    ./deploy/linux/build-and-test.sh

    current=$(git rev-parse --short HEAD)

    squashedversion=$(echo "$version" | sed 's/_-//g')

    mv deploy/linux/docker/output/VampPluginPackInstaller-"$current"-x86_64.AppImage \
	packages/vamp-plugin-pack-installer-"$squashedversion"
fi

echo "Done"

