#!/bin/bash

set -e

usage() {
    echo "Usage: $0 <plugin> [<plugin> ...]" 1>&2
    echo "       $0 <plugin-dir>" 1>&2
    exit 2
}    

first_arg="$1"

if [ -z "$first_arg" ]; then
    usage
fi

if [ -d "$first_arg" ] && [ -n "$2" ]; then
    usage
fi

paths=("$@")

set -u

sign() {
    path="$1"
    if [ -d /Applications ]; then
        codesign -s "Developer ID Application: Chris Cannam" -fv --options runtime "$path"
    fi
}

if [ -d "$first_arg" ]; then
    for path in "$first_arg"/*.{dll,so,dylib} ; do
        if [ -f "$path" ]; then
            sign "$path"
        fi
    done
    touch "$first_arg/.signed"
else
    for path in "${paths[@]}"; do
        if [ ! -f "$path" ]; then
            echo "ERROR: Path $path not found" 1>&2
            exit 1
        fi
    done
    for path in "${paths[@]}"; do
        sign "$path"
    done
fi

exit 0

