#!/bin/bash

set -e

if [ -z "$1" ]; then
    echo "Usage: $0 <plugin> [<plugin> ...]" 1>&2
    exit 2
fi

paths=("$@")

set -u

for path in "${paths[@]}"; do
    if [ ! -f "$path" ]; then
        echo "ERROR: Path $path not found" 1>&2
        exit 1
    fi
done

for path in "${paths[@]}"; do

    if [ -d /Applications ]; then
        codesign -s "Developer ID Application: Chris Cannam" -fv --options runtime "$path"
    fi

done

exit 0

