FROM ubuntu:22.04
MAINTAINER Chris Cannam <cannam@all-day-breakfast.com>
RUN apt-get update && \
    apt-get install -y \
    software-properties-common \
    build-essential \
    libbz2-dev \
    libfftw3-dev \
    libfishsound1-dev \
    libid3tag0-dev \
    liblo-dev \
    liblrdf0-dev \
    libmad0-dev \
    liboggz2-dev \
    libopus-dev \
    libopusfile-dev \
    libpulse-dev \
    libasound2-dev \
    libjack-dev \
    libsamplerate-dev \
    libsndfile-dev \
    libsord-dev \
    libxml2-utils \
    qt6-base-dev \
    qt6-pdf-dev \
    qt6-base-dev-tools \
    libboost-all-dev \
    libqt6svg6-dev \
    raptor2-utils \
    git \
    mercurial \
    autoconf \
    automake \
    libtool \
    lintian \
    curl \
    wget \
    unzip \
    smlnj \
    capnproto \
    libcapnp-dev \
    ninja-build \
    libglib2.0-dev \
    python3-pip

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8

# The explicit revision number here is to make sure the following git
# clone is not cached from a different revision
RUN echo Cloning revision [[REVISION]]

RUN git clone https://github.com/vamp-plugins/vamp-plugin-pack
WORKDIR vamp-plugin-pack
RUN git checkout [[REVISION]]

WORKDIR /root

COPY id_rsa_build .ssh/id_rsa_build
COPY known_hosts .ssh/known_hosts
RUN chmod 600 .ssh/id_rsa_build .ssh/known_hosts
RUN echo '{"accounts": {"sourcehut": "~breakfastquay"}}' > .repoint.json
RUN ( echo '[ui]' ; echo 'ssh = ssh -i /root/.ssh/id_rsa_build' ) > .hgrc

WORKDIR /vamp-plugin-pack

RUN REPOINT_INSECURE=1 ./repoint install
RUN qmake6 -r QMAKE_RCC="/usr/lib/qt6/libexec/rcc"
RUN make -j3

RUN deploy/linux/deploy-appimage.sh
RUN tar cvf output.tar *.AppImage && cp output.tar ..
